name: pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:

    - name: Build
      run: |
        echo 装包
        npm install
        echo 构建文档
        npm run docs:build
        echo 构建完成
        cpr docs-dist docs -o
        ls
